Cohort sub group classes
OHDSI/CohortGenerator pull request #65
Opened 2022-11-16 17:58 UTC by azimov

Work in progress.

Initial implementation of Cohort Subgroup R6 classes for serialisation.

Some Notes:
* Instead of using toJSON classes must implement toList  which can be serialized to json
* The design document was a little vague on how cohort subsets should work so the implementation is just a first pass. There was some hint that this should apply the subset based on already generated cohorts - this seemed a little strange to me as it's inflexible.
* There is no thought as to how different subsets are operated together, its currently just a list :
- The reality is that each subset operation should be mergabale with others (e.g. CohortSubsetA INTERSECTION CohortSubsetB UNION DemographicSubsetC) - this could get incredibly complicated...
* Documentation not implemented
* Tests are shallow (but validate most functionality)

2022-11-16 19:05 UTC, chrisknoll requested changes

2022-11-16 19:25 UTC, chrisknoll commented
Note on polymorphism in the types (ie: parent class of Subset, child classes CohortSubset, DemographicSubset, LimitCriteriaSubset, CirceCriteriaSubset.   JSON doesn't handle polymorphism at all so we have to use our own solution.   In the Java world, we use Jackson JSON API to define polymorphic types, and [there are several way to do it:](https://fasterxml.github.io/jackson-annotations/javadoc/2.4/com/fasterxml/jackson/annotation/JsonTypeInfo.html)

One way is to use a a special 'type attribute' of the json to indicate the type, and the JSON annotations in Java will look for that field in order to determine what the underlying implementing class should be instantiated.  This is the approach you took with your 'type' attribute, but I don't see anywhere in the code that would deserialize JSON into the correct R6 class (but this is related to my comment that you need an `initalize()` method , so it's simply a matter that deserialization isn't impelemnted.

The other way is to use the `WRAPPER_OBJECT` mode, where you specify a special name for the wrapper field which works very similar to 'type' except now you don't have any 'type' field polluting (no hyperbole intended) the JSON.   We use this approach in Circe Entry Events where the entry events are a List of Criteria objects:

```
{
  "entryEvents": [
  {
    "ConditionOccurrence": { ... fields of ConditionOccurrence... }
  },
  {
    "DrugExposure": {... fields of DrugExposure ... }
  }
  ]
... rest of cohort expression follows ...
}
```

So, when you're deserializing this JSON from R, you're gonig to get a list of lists:  first element is a list with 1 named element: ConditionOccurrence, the second element is a list with 1 named element: DrugExposure.  The deserializer will determien which R6 class to instantiate based on the value of that named element (and should throw an error if there are more than 1).

Same thing with Subsets you're defining:

```
subsetDefs : [
  {
    "CohortSubset" : { ... fields of CohortSubset ... }
  },
  {
    "DemograpicSubset" : { ... fields of DemographicSubset ... }
  },
  {
    "LimitSubset" : { ... fields of LimitSubset ... }
  }
]
```

For the SubsetDefinition, (again this is confusing: we have a subset type that uses cohorts to subset called CohortSubset, but a cohort that is yielded by performing a subset operation on it is a 'cohort subset'), we don't need polymorphism here:  a SubsetDefinition indicates an output cohort id, the target cohort to subset, and a subset definition (again, confusing!) that should be used to perform the subset.   But this section of JSON for this R6 class would look like this:

```
{
  cohortId: 101, // the resulting cohort id
  targetCohortId:  1, // the cohort to subset
  subsetId: 1 // the subset logic to use
}
```

This can be a collection of 'cohort subsets' but it's not polymorpic:  each element of this list is the same thing: a SubsetDefinition.  (Or maybe a CohortSubset, but we have a CohortSubset type already that defines creating a subset using cohorts!   Confusing!)

2022-12-06 21:42 UTC, azimov commented
See #67 for a brief description of the objectives

2022-12-15 21:07 UTC, anthonysena commented
@azimov thanks for the work here - I'm going to merge this into a feature branch on the CohortGenerator repo so that @chrisknoll and I can work on this collaboratively. I'll open a new draft PR with that new branch for us to keep working on this feature. Thanks!

2022-12-15 21:12 UTC, anthonysena approved these changes

2022-12-15 21:12 UTC, merged